OPENAI_API_KEY = "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"

GOOGLE_DRIVE_FOLDER_ID = "187pusW-uec4aTc-Icf-iOOy9JrwYUQgS"